// Comprehensive Mock Dataset for Standalone Frontend Execution

export const mockUsers = [
  { id: 1, name: 'Marcus Vance', email: 'admin@company.com', role: 'super_admin', status: 'active', last_login: '2026-10-05 10:26:15' },
  { id: 2, name: 'Elena Rostova', email: 'itadmin@company.com', role: 'it_admin', status: 'active', last_login: '2026-10-05 09:14:02' },
  { id: 3, name: 'James Thornton', email: 'manager@company.com', role: 'manager', status: 'active', last_login: '2026-10-04 18:30:10' },
  { id: 4, name: 'Chloe Simmons', email: 'viewer@company.com', role: 'viewer', status: 'active', last_login: '2026-10-04 14:12:45' },
  { id: 20, name: 'Alex Rivera', email: 'alex.rivera@company.com', role: 'laptop_owner', status: 'active', last_login: null }
];

export const mockDepartments = [
  { id: 1, name: 'Information Technology', code: 'IT', description: 'Core IT infrastructure and cybersecurity', device_count: 3, online_device_count: 2, employee_count: 2, budget_allocated: 185000, total_asset_value: 6929 },
  { id: 2, name: 'Engineering & DevOps', code: 'ENG', description: 'Software development, cloud systems, QA', device_count: 4, online_device_count: 3, employee_count: 3, budget_allocated: 320000, total_asset_value: 7398 },
  { id: 3, name: 'Finance & Accounting', code: 'FIN', description: 'Financial auditing, payroll, investor relations', device_count: 2, online_device_count: 1, employee_count: 1, budget_allocated: 95000, total_asset_value: 4350 },
  { id: 4, name: 'Human Resources', code: 'HR', description: 'Talent acquisition and people operations', device_count: 1, online_device_count: 0, employee_count: 1, budget_allocated: 60000, total_asset_value: 1420 },
  { id: 5, name: 'Sales & Partnerships', code: 'SALES', description: 'Enterprise accounts and client development', device_count: 2, online_device_count: 2, employee_count: 2, budget_allocated: 140000, total_asset_value: 4179 },
  { id: 6, name: 'Marketing & Growth', code: 'MKTG', description: 'Brand marketing, creative design, digital campaigns', device_count: 1, online_device_count: 1, employee_count: 1, budget_allocated: 85000, total_asset_value: 2499 },
  { id: 7, name: 'Operations & Logistics', code: 'OPS', description: 'Supply chain management and facility operations', device_count: 1, online_device_count: 0, employee_count: 1, budget_allocated: 110000, total_asset_value: 2850 },
  { id: 8, name: 'Legal & Compliance', code: 'LEGAL', description: 'Corporate law and regulatory compliance', device_count: 1, online_device_count: 1, employee_count: 1, budget_allocated: 50000, total_asset_value: 1299 }
];

export const mockEmployees = [
  { id: 1, employee_id: 'EMP-1001', name: 'Alex Rivera', email: 'alex.rivera@company.com', phone: '+1 (555) 234-5678', department_id: 2, department_name: 'Engineering & DevOps', branch: 'Headquarters (NY)', position: 'Lead Cloud Architect', status: 'active', assigned_devices_count: 1 },
  { id: 2, employee_id: 'EMP-1002', name: 'Sarah Jenkins', email: 'sarah.jenkins@company.com', phone: '+1 (555) 345-6789', department_id: 1, department_name: 'Information Technology', branch: 'Headquarters (NY)', position: 'Senior IT Systems Engineer', status: 'active', assigned_devices_count: 1 },
  { id: 3, employee_id: 'EMP-1003', name: 'David Miller', email: 'david.miller@company.com', phone: '+1 (555) 456-7890', department_id: 3, department_name: 'Finance & Accounting', branch: 'Chicago Hub', position: 'Senior Financial Analyst', status: 'active', assigned_devices_count: 1 },
  { id: 4, employee_id: 'EMP-1004', name: 'Emily Zhang', email: 'emily.zhang@company.com', phone: '+1 (555) 567-8901', department_id: 2, department_name: 'Engineering & DevOps', branch: 'San Francisco Office', position: 'Staff Backend Engineer', status: 'active', assigned_devices_count: 1 },
  { id: 5, employee_id: 'EMP-1005', name: 'Marcus Sterling', email: 'marcus.s@company.com', phone: '+1 (555) 678-9012', department_id: 5, department_name: 'Sales & Partnerships', branch: 'Headquarters (NY)', position: 'VP of Global Enterprise Sales', status: 'active', assigned_devices_count: 1 },
  { id: 6, employee_id: 'EMP-1006', name: 'Hannah Abbott', email: 'hannah.a@company.com', phone: '+1 (555) 789-0123', department_id: 4, department_name: 'Human Resources', branch: 'Headquarters (NY)', position: 'People Operations Specialist', status: 'active', assigned_devices_count: 1 },
  { id: 7, employee_id: 'EMP-1007', name: 'Liam O\'Connor', email: 'liam.oc@company.com', phone: '+44 20 7946 0912', department_id: 6, department_name: 'Marketing & Growth', branch: 'London Office', position: 'Senior Creative Director', status: 'active', assigned_devices_count: 1 },
  { id: 8, employee_id: 'EMP-1008', name: 'Sophia Patel', email: 'sophia.p@company.com', phone: '+1 (555) 890-1234', department_id: 2, department_name: 'Engineering & DevOps', branch: 'Austin Innovation Hub', position: 'Frontend Team Lead', status: 'active', assigned_devices_count: 1 },
  { id: 9, employee_id: 'EMP-1009', name: 'Nathan Drake', email: 'nathan.d@company.com', phone: '+1 (555) 901-2345', department_id: 7, department_name: 'Operations & Logistics', branch: 'Chicago Hub', position: 'Logistics Director', status: 'active', assigned_devices_count: 1 },
  { id: 10, employee_id: 'EMP-1010', name: 'Jessica Pearson', email: 'jessica.p@company.com', phone: '+1 (555) 912-3456', department_id: 8, department_name: 'Legal & Compliance', branch: 'Headquarters (NY)', position: 'Chief Legal Counsel', status: 'active', assigned_devices_count: 1 },
  { id: 11, employee_id: 'EMP-1011', name: 'Carlos Mendez', email: 'carlos.m@company.com', phone: '+1 (555) 923-4567', department_id: 1, department_name: 'Information Technology', branch: 'San Francisco Office', position: 'IT Support Specialist', status: 'active', assigned_devices_count: 1 },
  { id: 12, employee_id: 'EMP-1012', name: 'Aisha Khan', email: 'aisha.k@company.com', phone: '+65 6789 0123', department_id: 5, department_name: 'Sales & Partnerships', branch: 'Singapore Office', position: 'Regional Sales Director (APAC)', status: 'active', assigned_devices_count: 1 }
];

export const mockDevices = [
  {
    id: 1,
    device_id: 'DEV-WIN-A19F8321',
    asset_id: 'SG-LAP-001',
    name: "Alex's ThinkPad X1",
    hostname: 'WKSTN-NY-01',
    manufacturer: 'Lenovo',
    model: 'ThinkPad X1 Carbon Gen 11',
    serial_number: 'LNV-X1C-982144',
    os: 'Windows',
    os_version: 'Windows 11 Pro 23H2',
    architecture: 'x64',
    cpu_model: '13th Gen Intel Core i7-1365U (10 Cores, 12 Threads)',
    ram_total_gb: 32,
    storage_total_gb: 1024,
    employee_id: 1,
    employee_name: 'Alex Rivera',
    employee_code: 'EMP-1001',
    employee_position: 'Lead Cloud Architect',
    department_id: 2,
    department_name: 'Engineering & DevOps',
    department_code: 'ENG',
    branch: 'Headquarters (NY)',
    status: 'online',
    asset_status: 'assigned',
    battery_percent: 89,
    battery_status: 'Charging',
    cpu_usage: 14.5,
    ram_usage: 48.2,
    disk_usage: 52.4,
    public_ip: '198.51.100.42',
    local_ip: '192.168.1.105',
    mac_address: '00:1A:2B:3C:4D:5E',
    purchase_price: 1850,
    purchase_date: '2025-01-10',
    warranty_expiry: '2028-01-10',
    supplier: 'Lenovo Enterprise Direct',
    first_seen: '2025-01-15 10:00:00',
    last_seen: new Date(Date.now() - 25000).toISOString(),
    latest_location: { city: 'New York', region: 'New York', country: 'United States', latitude: 40.7128, longitude: -74.0060, isp: 'Verizon Enterprise Solutions' }
  },
  {
    id: 2,
    device_id: 'DEV-MAC-B82910CC',
    asset_id: 'SG-LAP-002',
    name: "Sarah's MacBook Pro 16",
    hostname: 'MBP-NY-SJ02',
    manufacturer: 'Apple',
    model: 'MacBook Pro 16" (M3 Max)',
    serial_number: 'C02G9012MD6R',
    os: 'macOS',
    os_version: 'macOS Sonoma 14.4.1',
    architecture: 'arm64',
    cpu_model: 'Apple M3 Max (16-core CPU, 40-core GPU)',
    ram_total_gb: 64,
    storage_total_gb: 2048,
    employee_id: 2,
    employee_name: 'Sarah Jenkins',
    employee_code: 'EMP-1002',
    employee_position: 'Senior IT Systems Engineer',
    department_id: 1,
    department_name: 'Information Technology',
    department_code: 'IT',
    branch: 'Headquarters (NY)',
    status: 'online',
    asset_status: 'assigned',
    battery_percent: 96,
    battery_status: 'Plugged In',
    cpu_usage: 8.2,
    ram_usage: 36.8,
    disk_usage: 41.5,
    public_ip: '198.51.100.42',
    local_ip: '192.168.1.112',
    mac_address: 'F4:D4:88:5A:9C:12',
    purchase_price: 3899,
    purchase_date: '2025-01-25',
    warranty_expiry: '2028-01-25',
    supplier: 'Apple Enterprise Store',
    first_seen: '2025-02-01 11:30:00',
    last_seen: new Date(Date.now() - 15000).toISOString(),
    latest_location: { city: 'New York', region: 'New York', country: 'United States', latitude: 40.7128, longitude: -74.0060, isp: 'Verizon Enterprise Solutions' }
  },
  {
    id: 3,
    device_id: 'DEV-WIN-C73928FA',
    asset_id: 'SG-LAP-003',
    name: "David's Dell XPS 15",
    hostname: 'WKSTN-CHI-DM03',
    manufacturer: 'Dell',
    model: 'XPS 15 9530',
    serial_number: 'DELL-XPS-482910',
    os: 'Windows',
    os_version: 'Windows 11 Enterprise',
    architecture: 'x64',
    cpu_model: '13th Gen Intel Core i9-13900H (14 Cores)',
    ram_total_gb: 32,
    storage_total_gb: 1024,
    employee_id: 3,
    employee_name: 'David Miller',
    employee_code: 'EMP-1003',
    employee_position: 'Senior Financial Analyst',
    department_id: 3,
    department_name: 'Finance & Accounting',
    department_code: 'FIN',
    branch: 'Chicago Hub',
    status: 'online',
    asset_status: 'assigned',
    battery_percent: 74,
    battery_status: 'Discharging',
    cpu_usage: 22.1,
    ram_usage: 61.4,
    disk_usage: 68.2,
    public_ip: '203.0.113.88',
    local_ip: '10.0.4.55',
    mac_address: '3C:52:82:7E:11:09',
    purchase_price: 2150,
    purchase_date: '2025-01-15',
    warranty_expiry: '2027-01-15',
    supplier: 'Dell Technologies Direct',
    first_seen: '2025-01-20 15:00:00',
    last_seen: new Date(Date.now() - 40000).toISOString(),
    latest_location: { city: 'Chicago', region: 'Illinois', country: 'United States', latitude: 41.8781, longitude: -87.6298, isp: 'AT&T Commercial Gateway' }
  },
  {
    id: 4,
    device_id: 'DEV-MAC-D629188E',
    asset_id: 'SG-LAP-004',
    name: "Emily's MacBook Air 15",
    hostname: 'MBA-SF-EZ04',
    manufacturer: 'Apple',
    model: 'MacBook Air 15" (M2)',
    serial_number: 'C02H1829KD9S',
    os: 'macOS',
    os_version: 'macOS Ventura 13.6.3',
    architecture: 'arm64',
    cpu_model: 'Apple M2 (8-core CPU, 10-core GPU)',
    ram_total_gb: 24,
    storage_total_gb: 512,
    employee_id: 4,
    employee_name: 'Emily Zhang',
    employee_code: 'EMP-1004',
    employee_position: 'Staff Backend Engineer',
    department_id: 2,
    department_name: 'Engineering & DevOps',
    department_code: 'ENG',
    branch: 'San Francisco Office',
    status: 'online',
    asset_status: 'assigned',
    battery_percent: 62,
    battery_status: 'Discharging',
    cpu_usage: 18.0,
    ram_usage: 54.0,
    disk_usage: 71.9,
    public_ip: '192.0.2.71',
    local_ip: '172.16.2.88',
    mac_address: 'A4:83:E7:22:90:31',
    purchase_price: 1699,
    purchase_date: '2025-02-05',
    warranty_expiry: '2027-02-05',
    supplier: 'Apple Enterprise Store',
    first_seen: '2025-02-10 12:00:00',
    last_seen: new Date(Date.now() - 30000).toISOString(),
    latest_location: { city: 'San Francisco', region: 'California', country: 'United States', latitude: 37.7749, longitude: -122.4194, isp: 'Comcast Business Communications' }
  },
  {
    id: 5,
    device_id: 'DEV-WIN-E910283A',
    asset_id: 'SG-LAP-005',
    name: "Marcus's HP EliteBook 840",
    hostname: 'WKSTN-NY-MS05',
    manufacturer: 'HP',
    model: 'EliteBook 840 G10',
    serial_number: 'HP-EB840-771920',
    os: 'Windows',
    os_version: 'Windows 11 Pro 23H2',
    architecture: 'x64',
    cpu_model: 'Intel Core i7-1370P vPro (14 Cores)',
    ram_total_gb: 32,
    storage_total_gb: 1024,
    employee_id: 5,
    employee_name: 'Marcus Sterling',
    employee_code: 'EMP-1005',
    employee_position: 'VP of Global Enterprise Sales',
    department_id: 5,
    department_name: 'Sales & Partnerships',
    department_code: 'SALES',
    branch: 'Headquarters (NY)',
    status: 'online',
    asset_status: 'assigned',
    battery_percent: 85,
    battery_status: 'Plugged In',
    cpu_usage: 11.4,
    ram_usage: 42.1,
    disk_usage: 49.3,
    public_ip: '198.51.100.42',
    local_ip: '192.168.1.144',
    mac_address: 'E8:6A:64:1B:77:99',
    purchase_price: 1780,
    purchase_date: '2025-01-12',
    warranty_expiry: '2028-01-12',
    supplier: 'CDW Corporate IT',
    first_seen: '2025-01-18 10:00:00',
    last_seen: new Date(Date.now() - 10000).toISOString(),
    latest_location: { city: 'New York', region: 'New York', country: 'United States', latitude: 40.7128, longitude: -74.0060, isp: 'Verizon Enterprise Solutions' }
  },
  {
    id: 6,
    device_id: 'DEV-WIN-F82910AB',
    asset_id: 'SG-LAP-006',
    name: "Hannah's ThinkPad T14s",
    hostname: 'WKSTN-NY-HA06',
    manufacturer: 'Lenovo',
    model: 'ThinkPad T14s Gen 4',
    serial_number: 'LNV-T14-662910',
    os: 'Windows',
    os_version: 'Windows 11 Pro 22H2',
    architecture: 'x64',
    cpu_model: 'AMD Ryzen 7 PRO 7840U (8 Cores)',
    ram_total_gb: 16,
    storage_total_gb: 512,
    employee_id: 6,
    employee_name: 'Hannah Abbott',
    employee_code: 'EMP-1006',
    employee_position: 'People Operations Specialist',
    department_id: 4,
    department_name: 'Human Resources',
    department_code: 'HR',
    branch: 'Headquarters (NY)',
    status: 'offline',
    asset_status: 'assigned',
    battery_percent: 45,
    battery_status: 'Discharging',
    cpu_usage: 0,
    ram_usage: 0,
    disk_usage: 58.1,
    public_ip: '198.51.100.42',
    local_ip: '192.168.1.189',
    mac_address: '28:D2:44:81:66:34',
    purchase_price: 1420,
    purchase_date: '2025-02-10',
    warranty_expiry: '2027-02-10',
    supplier: 'Lenovo Enterprise Direct',
    first_seen: '2025-02-15 14:00:00',
    last_seen: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    latest_location: { city: 'New York', region: 'New York', country: 'United States', latitude: 40.7128, longitude: -74.0060, isp: 'Verizon Enterprise Solutions' }
  },
  {
    id: 7,
    device_id: 'DEV-MAC-A71928CC',
    asset_id: 'SG-LAP-007',
    name: "Liam's MacBook Pro 14",
    hostname: 'MBP-LDN-LO07',
    manufacturer: 'Apple',
    model: 'MacBook Pro 14" (M2 Pro)',
    serial_number: 'C02J8819TD8K',
    os: 'macOS',
    os_version: 'macOS Sonoma 14.2',
    architecture: 'arm64',
    cpu_model: 'Apple M2 Pro (10-core CPU)',
    ram_total_gb: 32,
    storage_total_gb: 1024,
    employee_id: 7,
    employee_name: 'Liam O\'Connor',
    employee_code: 'EMP-1007',
    employee_position: 'Senior Creative Director',
    department_id: 6,
    department_name: 'Marketing & Growth',
    department_code: 'MKTG',
    branch: 'London Office',
    status: 'online',
    asset_status: 'assigned',
    battery_percent: 92,
    battery_status: 'Plugged In',
    cpu_usage: 15.3,
    ram_usage: 59.8,
    disk_usage: 64.1,
    public_ip: '81.2.69.142',
    local_ip: '192.168.20.45',
    mac_address: '70:EF:00:19:AA:88',
    purchase_price: 2499,
    purchase_date: '2025-01-20',
    warranty_expiry: '2027-01-20',
    supplier: 'Apple Enterprise UK',
    first_seen: '2025-01-28 11:00:00',
    last_seen: new Date(Date.now() - 50000).toISOString(),
    latest_location: { city: 'London', region: 'England', country: 'United Kingdom', latitude: 51.5074, longitude: -0.1278, isp: 'BT Global Services' }
  },
  {
    id: 8,
    device_id: 'DEV-WIN-B99210DD',
    asset_id: 'SG-LAP-008',
    name: "Sophia's Dell Latitude 5440",
    hostname: 'WKSTN-ATX-SP08',
    manufacturer: 'Dell',
    model: 'Latitude 5440',
    serial_number: 'DELL-LAT-992183',
    os: 'Windows',
    os_version: 'Windows 11 Pro 23H2',
    architecture: 'x64',
    cpu_model: '13th Gen Intel Core i7-1355U',
    ram_total_gb: 16,
    storage_total_gb: 512,
    employee_id: 8,
    employee_name: 'Sophia Patel',
    employee_code: 'EMP-1008',
    employee_position: 'Frontend Team Lead',
    department_id: 2,
    department_name: 'Engineering & DevOps',
    department_code: 'ENG',
    branch: 'Austin Innovation Hub',
    status: 'online',
    asset_status: 'assigned',
    battery_percent: 82,
    battery_status: 'Charging',
    cpu_usage: 29.4,
    ram_usage: 72.1,
    disk_usage: 93.4,
    public_ip: '66.249.64.10',
    local_ip: '10.20.1.77',
    mac_address: '18:66:DA:5F:44:EE',
    purchase_price: 1350,
    purchase_date: '2025-02-15',
    warranty_expiry: '2027-02-15',
    supplier: 'Dell Technologies Direct',
    first_seen: '2025-02-20 10:00:00',
    last_seen: new Date(Date.now() - 25000).toISOString(),
    latest_location: { city: 'Austin', region: 'Texas', country: 'United States', latitude: 30.2672, longitude: -97.7431, isp: 'Spectrum Enterprise' }
  },
  {
    id: 9,
    device_id: 'DEV-WIN-C11928EE',
    asset_id: 'SG-LAP-009',
    name: "Nathan's HP ZBook Power G10",
    hostname: 'WKSTN-CHI-ND09',
    manufacturer: 'HP',
    model: 'ZBook Power 15.6 G10',
    serial_number: 'HP-ZB-119284',
    os: 'Windows',
    os_version: 'Windows 11 Enterprise',
    architecture: 'x64',
    cpu_model: 'Intel Core i9-13900HK (14 Cores)',
    ram_total_gb: 64,
    storage_total_gb: 2048,
    employee_id: 9,
    employee_name: 'Nathan Drake',
    employee_code: 'EMP-1009',
    employee_position: 'Logistics Director',
    department_id: 7,
    department_name: 'Operations & Logistics',
    department_code: 'OPS',
    branch: 'Chicago Hub',
    status: 'offline',
    asset_status: 'assigned',
    battery_percent: 12,
    battery_status: 'Discharging',
    cpu_usage: 0,
    ram_usage: 0,
    disk_usage: 78.5,
    public_ip: '203.0.113.88',
    local_ip: '10.0.4.92',
    mac_address: 'D4:5D:64:99:A1:22',
    purchase_price: 2850,
    purchase_date: '2025-01-05',
    warranty_expiry: '2028-01-05',
    supplier: 'CDW Corporate IT',
    first_seen: '2025-01-10 16:00:00',
    last_seen: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    latest_location: { city: 'Chicago', region: 'Illinois', country: 'United States', latitude: 41.8781, longitude: -87.6298, isp: 'AT&T Commercial Gateway' }
  },
  {
    id: 11,
    device_id: 'DEV-WIN-G5521011',
    asset_id: 'SG-LAP-011',
    name: 'Lab ThinkPad P16s Gen 2',
    hostname: 'WKSTN-SF-CM11',
    manufacturer: 'Lenovo',
    model: 'ThinkPad P16s Gen 2',
    serial_number: 'LNV-P16S-552109',
    os: 'Windows',
    os_version: 'Windows 11 Pro 23H2',
    architecture: 'x64',
    cpu_model: 'Intel Core i7-1370P (14 Cores)',
    ram_total_gb: 32,
    storage_total_gb: 1024,
    employee_id: 11,
    employee_name: 'Carlos Mendez',
    employee_code: 'EMP-1011',
    employee_position: 'IT Support Specialist',
    department_id: 1,
    department_name: 'Information Technology',
    department_code: 'IT',
    branch: 'San Francisco Office',
    status: 'maintenance',
    asset_status: 'maintenance',
    battery_percent: 100,
    battery_status: 'Plugged In',
    cpu_usage: 0,
    ram_usage: 0,
    disk_usage: 44.1,
    public_ip: '192.0.2.71',
    local_ip: '172.16.2.105',
    mac_address: 'AC:BC:32:88:E1:44',
    purchase_price: 2050,
    purchase_date: '2025-02-12',
    warranty_expiry: '2027-02-12',
    supplier: 'Lenovo Enterprise Direct',
    first_seen: '2025-02-18 15:00:00',
    last_seen: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    latest_location: { city: 'San Francisco', region: 'California', country: 'United States', latitude: 37.7749, longitude: -122.4194, isp: 'Comcast Business Communications' }
  },
  {
    id: 13,
    device_id: 'DEV-WIN-J8819233',
    asset_id: 'SG-LAP-013',
    name: 'Spare ThinkPad L14 Gen 4',
    hostname: 'WKSTN-HQ-POOL-01',
    manufacturer: 'Lenovo',
    model: 'ThinkPad L14 Gen 4',
    serial_number: 'LNV-L14-881923',
    os: 'Windows',
    os_version: 'Windows 11 Pro 23H2',
    architecture: 'x64',
    cpu_model: 'AMD Ryzen 5 PRO 7530U',
    ram_total_gb: 16,
    storage_total_gb: 512,
    employee_id: null,
    employee_name: null,
    department_id: 1,
    department_name: 'Information Technology',
    department_code: 'IT',
    branch: 'Headquarters (NY)',
    status: 'offline',
    asset_status: 'available',
    battery_percent: 100,
    battery_status: 'Plugged In',
    cpu_usage: 0,
    ram_usage: 0,
    disk_usage: 18.0,
    public_ip: '198.51.100.42',
    local_ip: '192.168.1.200',
    mac_address: 'B8:27:EB:99:55:12',
    purchase_price: 980,
    purchase_date: '2025-03-10',
    warranty_expiry: '2027-03-10',
    supplier: 'Lenovo Enterprise Direct',
    first_seen: '2025-03-10 11:00:00',
    last_seen: new Date(Date.now() - 4 * 86400 * 1000).toISOString(),
    latest_location: { city: 'New York', region: 'New York', country: 'United States', latitude: 40.7128, longitude: -74.0060, isp: 'Verizon Enterprise Solutions' }
  }
];

export const mockStats = {
  total: 15,
  online: 9,
  offline: 4,
  maintenance: 2,
  assigned: 12,
  unassigned: 3,
  recently_seen: 11,
  active_alerts: 5,
  departments: mockDepartments,
  os_distribution: [
    { os: 'Windows', count: 10 },
    { os: 'macOS', count: 5 }
  ],
  maintenance_distribution: [
    { status: 'open', count: 2 },
    { status: 'in_progress', count: 1 },
    { status: 'completed', count: 1 }
  ]
};

export const mockAlerts = [
  {
    id: 1,
    device_id: 8,
    device_asset_id: 'SG-LAP-008',
    device_name: "Sophia's Dell Latitude 5440",
    alert_type: 'low_disk',
    severity: 'warning',
    title: 'High Disk Usage Detected',
    message: 'SG-LAP-008 (Sophia Patel) primary storage has reached 93.4% capacity (under 35 GB remaining).',
    status: 'active',
    created_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString()
  },
  {
    id: 2,
    device_id: 9,
    device_asset_id: 'SG-LAP-009',
    device_name: "Nathan's HP ZBook Power G10",
    alert_type: 'offline',
    severity: 'critical',
    title: 'Device Offline Beyond Threshold',
    message: 'SG-LAP-009 (Nathan Drake) has been offline for over 48 hours without scheduled maintenance notice.',
    status: 'active',
    created_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString()
  },
  {
    id: 3,
    device_id: 6,
    device_asset_id: 'SG-LAP-006',
    device_name: "Hannah's ThinkPad T14s",
    alert_type: 'offline',
    severity: 'warning',
    title: 'Device Recently Offline',
    message: 'SG-LAP-006 (Hannah Abbott) has not sent a heartbeat for 3 hours.',
    status: 'active',
    created_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString()
  }
];

export const mockMaintenance = [
  {
    id: 1,
    ticket_id: 'MNT-2026-001',
    device_id: 11,
    device_asset_id: 'SG-LAP-011',
    device_name: 'Lab ThinkPad P16s Gen 2',
    issue: 'Display backlight flickering intermittently on battery power',
    priority: 'high',
    status: 'in_progress',
    technician: 'Sarah Jenkins',
    notes: 'Replaced display EDP cable; running 24h stress test.',
    reported_date: new Date(Date.now() - 2 * 86400 * 1000).toISOString(),
    completed_date: null
  },
  {
    id: 2,
    ticket_id: 'MNT-2026-002',
    device_id: 8,
    device_asset_id: 'SG-LAP-008',
    device_name: "Sophia's Dell Latitude 5440",
    issue: 'Drive disk space exceeded 90% threshold; potential log leak',
    priority: 'high',
    status: 'open',
    technician: 'Carlos Mendez',
    notes: 'Investigating crash dump accumulation in user directory.',
    reported_date: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    completed_date: null
  }
];

export const mockNotifications = [
  { id: 1, title: 'Critical Device Offline', message: 'Device SG-LAP-009 has exceeded 48h offline threshold.', type: 'critical', is_read: 0, link: '/devices/9', created_at: new Date(Date.now() - 3600 * 1000).toISOString() },
  { id: 2, title: 'High Disk Usage Alert', message: 'Device SG-LAP-008 storage usage is critical at 93.4%.', type: 'warning', is_read: 0, link: '/devices/8', created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString() },
  { id: 3, title: 'New Maintenance Ticket', message: 'Ticket MNT-2026-002 assigned for Dell Precision.', type: 'info', is_read: 1, link: '/maintenance', created_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString() }
];

export const mockSettings = {
  company_name: 'Apex Global Technologies, Inc.',
  offline_threshold_minutes: '5',
  heartbeat_interval_seconds: '60',
  low_disk_threshold_percent: '90',
  low_battery_threshold_percent: '15',
  warranty_reminder_days: '30',
  admin_email: 'it-admin@company.com'
};

export const mockTokens = [
  { id: 1, token: 'ENROLL-CORP-2026-HQ01', name: 'HQ Global Bulk Enrollment', max_uses: 50, uses_count: 8, expires_at: new Date(Date.now() + 30 * 86400 * 1000).toISOString(), current_status: 'active' },
  { id: 2, token: 'ENROLL-VIP-EXEC-9921', name: 'Executive Tier Quick Setup', max_uses: 5, uses_count: 2, expires_at: new Date(Date.now() + 14 * 86400 * 1000).toISOString(), current_status: 'active' }
];

export const mockWorkSummary = {
  active_sessions: 4,
  software_titles: 22,
  events_today: 11,
  seconds_today: 28600,
  live: [
    { id: 1, device_id: 1, asset_id: 'SG-LAP-001', device_name: "Alex's ThinkPad X1", employee_name: 'Alex Rivera', department_name: 'Engineering & DevOps', windows_user: 'alex.rivera', app_name: 'Visual Studio Code', duration_seconds: 3000 },
    { id: 2, device_id: 2, asset_id: 'SG-LAP-002', device_name: "Sarah's MacBook Pro 16", employee_name: 'Sarah Jenkins', department_name: 'Information Technology', windows_user: 'sarah.jenkins', app_name: 'Slack', duration_seconds: 2400 },
    { id: 3, device_id: 3, asset_id: 'SG-LAP-003', device_name: "David's Dell XPS 15", employee_name: 'David Miller', department_name: 'Finance & Accounting', windows_user: 'david.miller', app_name: 'Microsoft Excel', duration_seconds: 7200 },
    { id: 4, device_id: 5, asset_id: 'SG-LAP-005', device_name: "Marcus's HP EliteBook 840", employee_name: 'Marcus Sterling', department_name: 'Sales & Partnerships', windows_user: 'marcus.sterling', app_name: 'Microsoft PowerPoint', duration_seconds: 1800 }
  ],
  top_software: [
    { app_name: 'Microsoft Excel', duration_seconds: 10800 },
    { app_name: 'Visual Studio Code', duration_seconds: 8400 },
    { app_name: 'Google Chrome', duration_seconds: 5400 },
    { app_name: 'Slack', duration_seconds: 2400 },
    { app_name: 'Microsoft PowerPoint', duration_seconds: 1800 }
  ]
};

export const mockActivities = [
  { id: 1, device_id: 1, asset_id: 'SG-LAP-001', employee_name: 'Alex Rivera', event_type: 'app_focus', app_name: 'Visual Studio Code', windows_user: 'alex.rivera', summary: 'alex.rivera started using Visual Studio Code', occurred_at: new Date(Date.now() - 50 * 60 * 1000).toISOString() },
  { id: 2, device_id: 2, asset_id: 'SG-LAP-002', employee_name: 'Sarah Jenkins', event_type: 'app_focus', app_name: 'Slack', windows_user: 'sarah.jenkins', summary: 'sarah.jenkins started using Slack', occurred_at: new Date(Date.now() - 40 * 60 * 1000).toISOString() },
  { id: 3, device_id: 3, asset_id: 'SG-LAP-003', employee_name: 'David Miller', event_type: 'screen_unlock', app_name: null, windows_user: 'david.miller', summary: 'david.miller unlocked the workstation', occurred_at: new Date(Date.now() - 150 * 60 * 1000).toISOString() },
  { id: 4, device_id: 3, asset_id: 'SG-LAP-003', employee_name: 'David Miller', event_type: 'app_focus', app_name: 'Microsoft Excel', windows_user: 'david.miller', summary: 'david.miller started using Microsoft Excel', occurred_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString() },
  { id: 5, device_id: 5, asset_id: 'SG-LAP-005', employee_name: 'Marcus Sterling', event_type: 'app_focus', app_name: 'Microsoft PowerPoint', windows_user: 'marcus.sterling', summary: 'marcus.sterling started using Microsoft PowerPoint', occurred_at: new Date(Date.now() - 30 * 60 * 1000).toISOString() },
  { id: 6, device_id: 6, asset_id: 'SG-LAP-006', employee_name: 'Hannah Abbott', event_type: 'session_end', app_name: null, windows_user: 'hannah.abbott', summary: 'hannah.abbott signed out', occurred_at: new Date(Date.now() - 20 * 3600 * 1000).toISOString() }
];

export const mockDeviceWork = {
  1: {
    current: { app_name: 'Visual Studio Code', windows_user: 'alex.rivera', duration_seconds: 3000 },
    software: [
      { name: 'Visual Studio Code', version: '1.95.0', publisher: 'Microsoft', is_running: 1 },
      { name: 'Google Chrome', version: '129.0', publisher: 'Google', is_running: 0 },
      { name: 'Microsoft Teams', version: '24231.0', publisher: 'Microsoft', is_running: 0 },
      { name: 'Slack', version: '4.40.0', publisher: 'Slack Technologies', is_running: 0 }
    ],
    usage_today: [
      { app_name: 'Visual Studio Code', duration_seconds: 3000 },
      { app_name: 'Microsoft Teams', duration_seconds: 3000 },
      { app_name: 'Google Chrome', duration_seconds: 8400 }
    ],
    activities: mockActivities.filter(item => item.device_id === 1)
  }
};

export const mockAuditLogs = [
  { id: 1, user_email: 'admin@company.com', action: 'USER_LOGIN', entity_type: 'USER', entity_id: '1', ip_address: '198.51.100.42', details: 'Successful administrator login', created_at: new Date(Date.now() - 3600 * 1000).toISOString() },
  { id: 2, user_email: 'itadmin@company.com', action: 'DEVICE_ASSIGNED', entity_type: 'DEVICE', entity_id: 'SG-LAP-010', ip_address: '198.51.100.42', details: 'Assigned SG-LAP-010 to Jessica Pearson', created_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString() },
  { id: 3, user_email: 'itadmin@company.com', action: 'MAINTENANCE_CREATED', entity_type: 'MAINTENANCE', entity_id: 'MNT-2026-001', ip_address: '198.51.100.42', details: 'Created ticket for ThinkPad display issue', created_at: new Date(Date.now() - 48 * 3600 * 1000).toISOString() }
];
